/**
 * AITestGenerator
 *
 * Uses the Claude API to generate semantically meaningful test scenarios from
 * an MCP server's capability definitions (tools, resources, prompts).
 *
 * Unlike the schema-driven SchemaInputGenerator (which generates syntactically
 * valid/invalid/fuzz inputs), AITestGenerator produces test collections that
 * mirror how a real user or agent would interact with the server — realistic
 * inputs, meaningful assertions, and domain-appropriate edge cases.
 *
 * ## Usage
 *
 * ```typescript
 * const gen = new AITestGenerator({ apiKey: process.env.ANTHROPIC_API_KEY });
 * const collection = await gen.generate(tools, resources, prompts, {
 *   serverCommand: "node dist/index.js",
 *   serverName: "My Notes Server",
 * });
 * writeFileSync("notes.checkspec.json", JSON.stringify(collection, null, 2));
 * ```
 *
 * ## How it works
 *
 * 1. Serialises the tool/resource/prompt schemas into a compact JSON payload.
 * 2. Sends a carefully engineered prompt to Claude asking for test scenarios.
 * 3. Parses the structured JSON response into a valid CheckSpecCollection.
 * 4. Falls back gracefully if the response can't be parsed.
 */

import Anthropic from "@anthropic-ai/sdk";
import type { Tool, Resource, Prompt } from "@modelcontextprotocol/sdk/types.js";
import type { CheckSpecCollection, TestCase } from "../runner/TestCollection.js";

// ── Public types ─────────────────────────────────────────────────────────────

export interface AIGenerateOptions {
  /**
   * Anthropic API key. Falls back to the ANTHROPIC_API_KEY environment
   * variable if omitted.
   */
  apiKey?: string;

  /**
   * Claude model ID to use for generation.
   * Defaults to claude-haiku-4-5-20251001 (fast, cheap, sufficient for JSON gen).
   * Use claude-sonnet-4-6 for more creative / nuanced scenarios.
   */
  model?: string;

  /**
   * Maximum number of test cases to request per capability type.
   * Defaults to 5 per tool.
   */
  maxTestsPerTool?: number;

  /**
   * Whether to include security-scan tests in the generated collection.
   * Defaults to true.
   */
  includeSecurity?: boolean;
}

export interface GenerateContext {
  /** The shell command used to start the server (used in the collection's server field). */
  serverCommand: string;
  /** Human-readable server name for the collection's `name` field. */
  serverName?: string;
  /** Working directory for the server process (forwarded to collection). */
  cwd?: string;
}

// ── AITestGenerator ───────────────────────────────────────────────────────────

export class AITestGenerator {
  private client: Anthropic;
  private model: string;
  private maxTestsPerTool: number;
  private includeSecurity: boolean;

  constructor(options: AIGenerateOptions = {}) {
    const apiKey = options.apiKey ?? process.env.ANTHROPIC_API_KEY;
    if (!apiKey) {
      throw new Error(
        "Anthropic API key is required. Set ANTHROPIC_API_KEY environment variable or pass apiKey option."
      );
    }
    this.client = new Anthropic({ apiKey });
    this.model = options.model ?? "claude-haiku-4-5-20251001";
    this.maxTestsPerTool = options.maxTestsPerTool ?? 5;
    this.includeSecurity = options.includeSecurity ?? true;
  }

  /**
   * Generate a complete CheckSpecCollection for the given server capabilities.
   *
   * @param tools      Tools returned by MCPRecordingClient.listTools()
   * @param resources  Resources returned by MCPRecordingClient.listResources()
   * @param prompts    Prompts returned by MCPRecordingClient.listPrompts()
   * @param context    Server connection details for the collection header
   */
  async generate(
    tools: Tool[],
    resources: Resource[],
    prompts: Prompt[],
    context: GenerateContext
  ): Promise<CheckSpecCollection> {
    const capabilitySummary = buildCapabilitySummary(tools, resources, prompts);
    const rawTests = await this.callClaude(capabilitySummary, tools, resources, prompts);

    // Always add the protocol handshake first
    const protocolTest: TestCase = {
      id: "protocol-init",
      name: "Initialization handshake",
      type: "protocol",
      tags: ["protocol"],
    };

    const [command, ...args] = context.serverCommand.split(" ");
    const serverName =
      context.serverName ?? guessServerName(context.serverCommand);

    return {
      version: "1.0",
      name: `${serverName} — AI-generated collection`,
      description:
        `Auto-generated by checkspec generate using Claude (${this.model}). ` +
        `Tools: ${tools.length}, Resources: ${resources.length}, Prompts: ${prompts.length}. ` +
        `Edit this file to refine assertions and add domain-specific expectations.`,
      server: {
        command,
        args,
        cwd: context.cwd,
      },
      tests: [protocolTest, ...rawTests],
    };
  }

  // ── Private helpers ─────────────────────────────────────────────────────────

  private async callClaude(
    summary: string,
    tools: Tool[],
    resources: Resource[],
    prompts: Prompt[]
  ): Promise<TestCase[]> {
    const systemPrompt = buildSystemPrompt();
    const userPrompt = buildUserPrompt(
      summary,
      tools,
      resources,
      prompts,
      this.maxTestsPerTool,
      this.includeSecurity
    );

    const message = await this.client.messages.create({
      model: this.model,
      max_tokens: 8192,
      system: systemPrompt,
      messages: [{ role: "user", content: userPrompt }],
    });

    const rawText =
      message.content[0].type === "text" ? message.content[0].text : "";

    return parseClaudeResponse(rawText, tools, resources, prompts);
  }
}

// ── Prompt builders ───────────────────────────────────────────────────────────

function buildSystemPrompt(): string {
  return `You are an expert QA engineer specialising in MCP (Model Context Protocol) server testing.

Your task is to generate a realistic, comprehensive set of test cases for an MCP server.
The tests must be returned as a JSON array of CheckSpec TestCase objects — nothing else.

## TestCase schema

\`\`\`typescript
interface TestCase {
  id: string;          // kebab-case, unique, e.g. "create-note-minimal"
  name: string;        // human-readable, e.g. "create_note › minimal required fields"
  type: "tool-call" | "resource-read" | "prompt-get" | "security";
  tool?: string;       // required for tool-call, security
  input?: Record<string, unknown>;  // required for tool-call (match tool's inputSchema)
  uri?: string;        // required for resource-read
  promptName?: string; // required for prompt-get
  promptArgs?: Record<string, string>;  // optional prompt arguments
  securityThreshold?: "critical" | "high" | "medium" | "low";
  expect?: {
    success?: boolean;
    contains?: string;  // substring the text response must contain
    schema?: object;    // JSON Schema the parsed JSON response must match
  };
  tags?: string[];
}
\`\`\`

## Rules for generating good tests

1. **Happy path first** — at least one success case per tool with realistic data.
2. **Error paths** — test invalid inputs, missing required fields, non-existent IDs.
3. **Round trips** — if a tool creates data, test reading it back; if it updates, verify the update.
4. **Realistic inputs** — use plausible domain values (not "foo", "bar", "test123").
5. **Schema assertions** — for tools that return structured JSON, include a \`schema\` assertion.
6. **contains assertions** — check for a key string in the response text.
7. **Security tests** — add a security test for any tool that echoes user input in errors.
8. **Tags** — always include at least one tag; use: tool, resource, prompt, error-handling, round-trip, security.
9. **IDs** — must be unique across all tests.

Return ONLY the JSON array. No markdown fences, no explanation.`;
}

function buildUserPrompt(
  summary: string,
  tools: Tool[],
  resources: Resource[],
  prompts: Prompt[],
  maxTestsPerTool: number,
  includeSecurity: boolean
): string {
  const toolsJson = JSON.stringify(
    tools.map((t) => ({
      name: t.name,
      description: t.description,
      inputSchema: t.inputSchema,
    })),
    null,
    2
  );

  const resourcesJson =
    resources.length > 0
      ? JSON.stringify(
          resources.map((r) => ({ name: r.name, uri: r.uri, description: r.description })),
          null,
          2
        )
      : "[]";

  const promptsJson =
    prompts.length > 0
      ? JSON.stringify(
          prompts.map((p) => ({ name: p.name, description: p.description, arguments: p.arguments })),
          null,
          2
        )
      : "[]";

  return `Generate test cases for this MCP server.

## Server capabilities

${summary}

## Tools (${tools.length})
${toolsJson}

## Resources (${resources.length})
${resourcesJson}

## Prompts (${prompts.length})
${promptsJson}

## Instructions

- Generate up to ${maxTestsPerTool} test cases per tool (happy path + error paths + round trips where applicable).
- Generate 1 test case per resource (type: "resource-read").
- Generate 1 test case per prompt (type: "prompt-get") with realistic argument values.
${includeSecurity ? '- Add a "security" type test for any tool that accepts string inputs (check for prompt-injection passthrough).' : ""}
- Do NOT include a protocol-init test (it will be added automatically).

Return ONLY the JSON array of TestCase objects.`;
}

// ── Response parser ───────────────────────────────────────────────────────────

/**
 * Parse Claude's JSON response into TestCase[].
 * Strips any markdown code fences and falls back to schema-driven defaults
 * if parsing fails.
 */
function parseClaudeResponse(
  raw: string,
  tools: Tool[],
  resources: Resource[],
  prompts: Prompt[]
): TestCase[] {
  // Strip markdown fences if Claude added them despite the instruction
  const stripped = raw
    .replace(/^```(?:json)?\s*/m, "")
    .replace(/\s*```\s*$/m, "")
    .trim();

  try {
    const parsed = JSON.parse(stripped) as unknown;
    if (!Array.isArray(parsed)) {
      throw new Error("Expected a JSON array");
    }
    // Basic validation and sanitisation of each item
    return parsed
      .filter((item): item is Record<string, unknown> => typeof item === "object" && item !== null)
      .map((item, index) => sanitizeTestCase(item, index));
  } catch {
    // Fallback: generate minimal tests without AI
    return generateFallbackTests(tools, resources, prompts);
  }
}

/** Sanitise a raw parsed object into a valid TestCase. */
function sanitizeTestCase(raw: Record<string, unknown>, index: number): TestCase {
  const type = (raw.type as string) ?? "tool-call";
  const id = typeof raw.id === "string" && raw.id ? raw.id : `test-${index + 1}`;
  const name = typeof raw.name === "string" && raw.name ? raw.name : `Test ${index + 1}`;

  const base: TestCase = { id, name, type: type as TestCase["type"] };

  if (typeof raw.tool === "string") base.tool = raw.tool;
  if (raw.input && typeof raw.input === "object") base.input = raw.input as Record<string, unknown>;
  if (typeof raw.uri === "string") base.uri = raw.uri;
  if (typeof raw.promptName === "string") base.promptName = raw.promptName;
  if (raw.promptArgs && typeof raw.promptArgs === "object")
    base.promptArgs = raw.promptArgs as Record<string, string>;
  if (typeof raw.securityThreshold === "string")
    base.securityThreshold = raw.securityThreshold as TestCase["securityThreshold"];
  if (raw.expect && typeof raw.expect === "object") base.expect = raw.expect as TestCase["expect"];
  if (Array.isArray(raw.tags)) base.tags = raw.tags as string[];

  return base;
}

/**
 * Minimal fallback when Claude's response can't be parsed.
 * Generates one basic test per tool/resource/prompt.
 */
function generateFallbackTests(
  tools: Tool[],
  resources: Resource[],
  prompts: Prompt[]
): TestCase[] {
  const tests: TestCase[] = [];

  for (const tool of tools) {
    tests.push({
      id: `tool-${tool.name}-basic`,
      name: `${tool.name} › basic call`,
      type: "tool-call",
      tool: tool.name,
      input: {},
      expect: { success: true },
      tags: ["tool", tool.name],
    });
  }

  for (const resource of resources) {
    tests.push({
      id: `resource-${resource.name}`,
      name: `${resource.name} › read`,
      type: "resource-read",
      uri: resource.uri,
      tags: ["resource"],
    });
  }

  for (const prompt of prompts) {
    tests.push({
      id: `prompt-${prompt.name}`,
      name: `${prompt.name} › get`,
      type: "prompt-get",
      promptName: prompt.name,
      tags: ["prompt"],
    });
  }

  return tests;
}

// ── Utility ───────────────────────────────────────────────────────────────────

function buildCapabilitySummary(
  tools: Tool[],
  resources: Resource[],
  prompts: Prompt[]
): string {
  const parts: string[] = [];
  if (tools.length > 0) {
    parts.push(`Tools: ${tools.map((t) => t.name).join(", ")}`);
  }
  if (resources.length > 0) {
    parts.push(`Resources: ${resources.map((r) => r.name).join(", ")}`);
  }
  if (prompts.length > 0) {
    parts.push(`Prompts: ${prompts.map((p) => p.name).join(", ")}`);
  }
  return parts.join(" | ");
}

function guessServerName(serverCommand: string): string {
  const parts = serverCommand.split(" ");
  const lastPart = parts[parts.length - 1] ?? serverCommand;
  // Strip path and extension: "node demos/notes-server/dist/index.js" → "notes-server"
  const segments = lastPart.replace(/\\/g, "/").split("/");
  for (let i = segments.length - 2; i >= 0; i--) {
    const seg = segments[i];
    if (seg && seg !== "dist" && seg !== "src" && seg !== ".") {
      return seg
        .replace(/[-_]server$/, "")
        .replace(/[-_]/g, " ")
        .replace(/\b\w/g, (c) => c.toUpperCase())
        + " Server";
    }
  }
  return "MCP Server";
}
